### ISSUE TITLE
Feature request: Memory maps side by side

### ISSUE THREAD

**Issue by KanedaFr** [raulgotor/linkerscope#25]
I'd like to be able to draw several maps side by side, with addresses aligned.
Some systems have a memory map which switches based on a register value or the data loaded

For exemple:
NEC PC88 -> http://www.maroon.dti.ne.jp/youkan/pc88/memmap.html
Atari Lynx -> https://atarilynxdeveloper.wordpress.com/2014/09/10/programming-tutorial-part-18files/

As workaround, I could use a basic map + links  but it won't produce the same result (ie not aligned side by side)
so I had to code a map per file and externally glue them together

**Comment by KanedaFr** [comment]
I added a 'visibility' attribute to Style, this way I could
- define each memory segment, even if they overlap
- draw areas when I select sections I want to be drawn

This is not a perfect mod since visibility should be handled on every object, like the real SVG visibility attribute (not a 'flag' for linkerscope) but it does what I want, waiting for your official update (if ever)

**Comment by raulgotor** [comment]
Hello @KanedaFr and thank you for your suggestion.

There is a hacky workaround that does what you want while still memory aligned:

Assuming you have all the sections you want to display in the different areas / views at your `map.yaml` file:
Create at least two areas, same size, at same `y` and one next to each other, with the same `range`. You can as well make use of the `start` and `end` attributes, which forces the area to display a specific memory range even if not used.

Then, under the `sections` section of each area, you list the section/s you would like to **hide** in that specific area and make its `size` 0:

```
- area:
    ...
    start: 0xE803F000
    end: 0xE8045000
    range: [0xE8040000, 0xE8044000]
    ...
    sections:
    - names: [ ROM Table, TPIU ] # This will hide these sections at this area
      size: 0
```

Repeat this for the other areas.

This way you can handle the visibility for a bunch of sections in one go by putting them in the `names` array.

Please find below as an example a configuration file that does what you want. Put the snippet below in a `.yaml` file and use it together with the yaml map file available at `examples/labels_map.yaml`. `./linkerscope.py examples/labels_map.yaml -c your_config.yaml`

```
# your_config.yaml
size: [1400, 300]
style:
  hide-address: true

areas:
- area:
    size: [ 200, 200 ]
    pos: [200]
    start: 0xE803F000
    end: 0xE8045000
    range: [0xE8040000, 0xE8044000]
    sections:
    - names: [ ROM Table, TPIU ]
      size: 0

- area:
    size: [ 200, 200 ]
    pos: [500]
    start: 0xE803F000
    end: 0xE8045000
    sections:
    - names: [ ETM, External PPB, Peripheral ]
      size: 0

- area:
    size: [ 200, 200 ]
    pos: [800]
    start: 0xE803F000
    end: 0xE8045000
    range: [0xE8040000, 0xE8044000]
    sections:
    - names: [ ROM Table ]
      size: 0

links:
   addresses: [ 0xE8041000, 0xe8043000 ]
```

Let me know if that would be an acceptable way. If yes, I can add the `hidden` attribute so it is not as hacky as doing `size` = 0.

Other solution would be doing everything on the same area, and in the `sections` subsection, defining `x` offsets per section, so they shift to the sides.
